name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t p1 ./p1
    - name: Run docker image
      run: docker run docker run -p 8080:8080 p1
